In [1]:
import numpy as np

In [31]:
# creates a 3x3 array with numbers form 1 to 9

z = np.arange(1,10)
x = z.reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
# creates a 2x2x2 array with random numbers

z = np.random.rand(2,2,2)
z

array([[[0.13691227, 0.88705721],
        [0.46339331, 0.97070482]],

       [[0.31164461, 0.65060824],
        [0.14498403, 0.99000407]]])

In [34]:
# Creates a border filled with 0's around an existing array

one = np.ones((4,4))
border = np.pad(one, pad_width=1, mode='constant', constant_values=0)
border

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [43]:
# creates a 8x8 array with a checkboard pattern (with 0's and 1's)

checkboard = np.ones((8,8))

checkboard[1::2, ::2] = 0
checkboard[::2, 1::2] = 0

checkboard

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [47]:
# creates a random vector of size 8 and replace the maximum value with 0

vector = np.random.rand(8)

vector

array([0.0302467 , 0.67183048, 0.32479536, 0.83967236, 0.00964397,
       0.27482861, 0.32504073, 0.31463125])