In [2]:
import numpy as np
n = 0
# Beispielbild (5x5)
image = np.array([
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0]])

# Sobel-Filter für Kanten
kernel = np.array([
    [1, 0, 0]
])

# Kernelgröße
k_height, k_width = kernel.shape
i_height, i_width = image.shape

# Output-Bild initialisieren
output = np.zeros((i_height - k_height + 1, i_width - k_width + 1))

# Kernel anwenden
for i in range(i_height - k_height + 1):
    for j in range(i_width - k_width + 1):
        # Bildausschnitt auswählen, der mit dem Kernel gefaltet wird
        region = image[i:i + k_height, j:j + k_width]
        n +=1 
        # Faltung: Punktprodukt von Kernel und Bildausschnitt
        output[i, j] = np.sum(region * kernel)
        
        print(output)

print("Gefaltetes Bild:\n", output)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
Gefaltetes Bild:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
import numpy as np
from scipy.ndimage import convolve, correlate

# Funktion, um eine 5x5 Matrix mit einer 1 in der Mitte zu erstellen
def create_test_matrix():
    matrix = np.zeros((5, 5), dtype=int)
    matrix[2, 2] = 1
    return matrix

# Funktion, um einen beliebigen 1D-Filter auf die Matrix anzuwenden
def apply_filter(matrix, f, mode="correlation"):
    # Erstelle eine 2D-Version des 1D-Filters (als Spalte) für die Anwendung
    kernel_2d = np.zeros((1, len(f)))
    kernel_2d[0, :] = f

    if mode == "correlation":
        # Korrelation anwenden
        result = correlate(matrix, kernel_2d, mode='constant', cval=0)
    elif mode == "convolution":
        # Faltung anwenden
        result = convolve(matrix, kernel_2d, mode='constant', cval=0)
    else:
        raise ValueError("Modus muss entweder 'correlation' oder 'convolution' sein.")

    return result

# Testen der Funktion
matrix = create_test_matrix()
f = [0, 0, 1]  # Beispiel-Filter

print("Originale Matrix:")
print(matrix)

# Korrelation
correlated_matrix = apply_filter(matrix, f, mode="correlation")
print("\nErgebnis der Korrelation:")
print(correlated_matrix)

# Faltung
convoluted_matrix = apply_filter(matrix, f, mode="convolution")
print("\nErgebnis der Faltung:")
print(convoluted_matrix)


Originale Matrix:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

Ergebnis der Korrelation:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

Ergebnis der Faltung:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [4]:
import numpy as np
from scipy.ndimage import convolve, correlate

# Funktion, um eine 5x5 Matrix mit einer 1 in der Mitte zu erstellen
def create_test_matrix():
    matrix = np.zeros((5, 5), dtype=int)
    matrix[2, 2] = 1
    return matrix

# Funktion, um einen beliebigen 1D-Filter auf die Matrix anzuwenden
def apply_filter(matrix, f, mode="correlation"):
    # Erstelle eine 2D-Version des 1D-Filters (als Zeile) für die Anwendung
    kernel_2d = np.zeros((1, len(f)))
    kernel_2d[0, :] = f

    if mode == "correlation":
        # Korrelation anwenden
        result = correlate(matrix, kernel_2d, mode='constant', cval=0)
    elif mode == "convolution":
        # Faltung anwenden
        # Um sicherzustellen, dass die Faltung den Effekt der Kernel-Drehung zeigt,
        # drehen wir das Kernel manuell.
        kernel_2d = np.flip(kernel_2d)
        result = convolve(matrix, kernel_2d, mode='constant', cval=0)
    else:
        raise ValueError("Modus muss entweder 'correlation' oder 'convolution' sein.")

    return result

# Testen der Funktion
matrix = create_test_matrix()
f = [0, 0, 1]  # Beispiel-Filter

print("Originale Matrix:")
print(matrix)

# Korrelation
correlated_matrix = apply_filter(matrix, f, mode="correlation")
print("\nErgebnis der Korrelation:")
print(correlated_matrix)

# Faltung
convoluted_matrix = apply_filter(matrix, f, mode="convolution")
print("\nErgebnis der Faltung:")
print(convoluted_matrix)


Originale Matrix:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

Ergebnis der Korrelation:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

Ergebnis der Faltung:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [5]:
import numpy as np
from scipy.ndimage import convolve1d

# Original 5x5 matrix with 1 in the center
original_matrix = np.array([
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0]
])

# Define the filter f = (0, 0, 1)
filter_1d = np.array([0, 0, 1])

# Apply the filter as a convolution
convolution_matrix = np.apply_along_axis(lambda m: convolve1d(m, filter_1d, mode='constant'), axis=1, arr=original_matrix)

# Apply the filter as a correlation
correlation_matrix = np.apply_along_axis(lambda m: np.correlate(m, filter_1d, mode='same'), axis=1, arr=original_matrix)

print("Original Matrix:")
print(original_matrix)
print("\nMatrix nach Faltung (Filterung nach links):")
print(convolution_matrix)
print("\nMatrix nach Korrelation (Filterung nach rechts):")
print(correlation_matrix)


Original Matrix:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

Matrix nach Faltung (Filterung nach links):
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

Matrix nach Korrelation (Filterung nach rechts):
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
