In [15]:
import numpy as np
n = 0
# Beispielbild (5x5)
image = np.array([
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0]
])

# Sobel-Filter für Kanten
kernel = np.array([
    [0, 0, 1],
    [1, 1, 1],
    [0, 0, 1]
])

# Kernelgröße
k_height, k_width = kernel.shape
i_height, i_width = image.shape

# Output-Bild initialisieren
output = np.zeros((i_height - k_height + 1, i_width - k_width + 1))

# Kernel anwenden
for i in range(i_height - k_height + 1):
    for j in range(i_width - k_width + 1):
        # Bildausschnitt auswählen, der mit dem Kernel gefaltet wird
        region = image[i:i + k_height, j:j + k_width]
        n +=1 
        # Faltung: Punktprodukt von Kernel und Bildausschnitt
        output[i, j] = np.sum(region * kernel)
        
        print(output)

print("Gefaltetes Bild:\n", output)


[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [1. 1. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [1. 1. 1.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [1. 1. 1.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [1. 1. 1.]
 [1. 0. 0.]]
Gefaltetes Bild:
 [[1. 0. 0.]
 [1. 1. 1.]
 [1. 0. 0.]]
