In [1]:
import numpy as np

In [2]:
arr = np.arange(1, 10).reshape((3,3))
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr = np.random.rand(2,2,2)
arr

array([[[0.0477234 , 0.71026183],
        [0.31240207, 0.33929984]],

       [[0.69713096, 0.58217222],
        [0.20298121, 0.96263963]]])

In [9]:
arr = np.ones((4,4))
bordered = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
bordered

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [29]:
arr = np.zeros((8,8))
arr[1::2, ::2] = 1
arr[::2, 1::2] = 1
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [37]:
vec = np.random.rand(8) #erstellt den vektor der größe 8
max_index = np.argmax(vec)  #np.argmax(vec) gibt den maximalen Wert des Vektors vec zurück

vec[max_index] = 0

vec 

array([0.32715716, 0.53439816, 0.19494839, 0.26183878, 0.87901381,
       0.84938545, 0.12102133, 0.        ])

In [38]:
x = np.array([8,25,25,15,21,4,21,29])

closest_idx = np.abs(x-17).argmin()

closest_val = x[closest_idx]

closest_val

15

In [45]:
x = np.random.rand(4, 8)
row_means = x.mean(axis=1, keepdims=True)
x_centered = x - row_means
x_centered

array([[-0.23473571,  0.35335597, -0.18151672,  0.08257077, -0.37548552,
         0.309431  ,  0.05915014, -0.01276994],
       [-0.23719516,  0.08212708, -0.24847714, -0.0861115 ,  0.16105185,
         0.27141611,  0.3169678 , -0.25977904],
       [ 0.17162505,  0.34175324, -0.05412923, -0.16811181, -0.418637  ,
        -0.19488315,  0.1889798 ,  0.13340311],
       [-0.260762  ,  0.42042998,  0.41225395, -0.29243645, -0.24003949,
         0.21219551, -0.33640516,  0.08476366]])